ALTER TABLE `fr_global_informe` CHANGE `id_frGlobal` `id_frGlobal`  INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `seguim_incomp_detall` CHANGE `id_seg_inc_det` `id_seg_inc_det` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `seguim_incomp_resum` CHANGE `id_seg_inc_res` `id_seg_inc_res` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE `control` CHANGE `clase_control` `clase_control_CA` VARCHAR(30) NOT NULL;
ALTER TABLE `control` ADD COLUMN `clase_control_ES` VARCHAR(30) NOT NULL AFTER `clase_control_CA`;
ALTER TABLE `excepcio` CHANGE `id_excepcio`  `id_excepcio` INT NOT NULL AUTO_INCREMENT;
ALTER TABLE aplicacions_obsoletes ADD COLUMN `modulo` VARCHAR(16) after `aplicacio`;
ALTER TABLE `germanar` CHANGE `id_germanar` `id_germanar` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `regles_bloqueig` CHANGE `id_regla` `id_regla` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `control` CHANGE `id_control` `id_control` INT(11) NOT NULL;
ALTER TABLE `control_literal` CHANGE `id_control_literal` `id_control_literal` INT(11) NOT NULL AUTO_INCREMENT;
