properties={
  "ProjectName":"cbpclo",
  "Author":"aperisza",
  "tableName":"control_literal",
  "ProcessName":"ModeloControlLiteral",
  "DataTable":"false",
  "idMain":"id_control_literal",
  "Model":[
    {"name":"expresioRegular","type":"String"},
    {"name":"ordre","type":"String"},
    {"name":"id_control_literal","type":"String"},
    {"name":"descripcio","type":"String"},
    {"name":"id_control","type":"String"},
    {"name":"tipo_accion","type":"String"},
  ],
   "InPOJO":[
     {"name":"expresioRegular","type":"String"},
     {"name":"ordre","type":"String"},
     {"name":"id_control_literal","type":"String"},
     {"name":"descripcio","type":"String"},
     {"name":"id_control","type":"String"},
     {"name":"tipo_accion","type":"String"}
   ],
  "InDTO":[
    {"name":"expresioRegular","type":"String"},
    {"name":"ordre","type":"String"},
    {"name":"id_control_literal","type":"String"},
    {"name":"descripcio","type":"String"},
    {"name":"id_control","type":"String"},
    {"name":"tipo_accion","type":"String"}
  ],
  "OutDTO":[
      {"name":"expresioRegular","type":"String"},
      {"name":"ordre","type":"String"},
      {"name":"id_control_literal","type":"String"},
      {"name":"descripcio","type":"String"},
      {"name":"id_control","type":"String"},
      {"name":"tipo_accion","type":"String"}
  ]
}
